### ISSUE TITLE
onMessage sends empty string if no return

### ISSUE THREAD

**Issue by webonix** [lucee/extension-websocket#6]
it looks like **onMessage()** and **onOpen()** sends an empty string if there is no `return`

I have had to add
```
    return serializeJSON(messageReceived); // does Lucee return empty string if no return ???
```

**Comment by michaeloffner** [comment]
the extension itself return null with "onMessage"  if the message is null
![Screenshot 2024-05-06 at 14 51 47](https://github.com/lucee/extension-websocket/assets/10769446/9f80e4a8-c266-4121-b9ec-1cb5d4e95a2d)

**Comment by michaeloffner** [comment]
onOpen is void anyway, so impossible to even return a value
![Screenshot 2024-05-06 at 14 53 35](https://github.com/lucee/extension-websocket/assets/10769446/55190dc8-8235-4b7b-aac4-ac8c9e927233)

**Comment by michaeloffner** [comment]
@webonix is that still an issue for you or can we close it?

**Comment by webonix** [comment]
@michaeloffner seems reasonable to me - I will close thicet

thank you
